### ISSUE TITLE
Layout needs adjustment for smaller screens

### ISSUE THREAD

**Issue by luk-str** [gdhebling/my-portfolio#3]
Hey Guilherme! 👋🏻

Just wanted to let you know that there are some layout issues you might want to look at when viewing the website on a small screen 📱

Here are some screenshots from iPhone SE (1st gen) which has a 4 inch retina screen.

### Running in _Safari_:

![Running in Safari](https://user-images.githubusercontent.com/65243622/106493169-13de5f80-64b9-11eb-985a-3f25814c9626.jpg)

# 

### Running in _Brave Browser_ with tabs open:

![IMG_1221](https://user-images.githubusercontent.com/65243622/106493346-5011c000-64b9-11eb-97c0-3547f7dcadd7.PNG)

# 

Should be an easy fix 😊

**Comment by gdhebling** [comment]
Hei Lukas! 👋

Thanks for reaching out! I appreciate you taking the time to make the suggestions. 😊
Today I finished porting the website from pure HTML/CSS/JS to Gatsby, so I probably messed some things in the process... 😅

I will take a look at the issues you mentioned!

All the best,
Guilherme

________________________________

**Comment by luk-str** [comment]
No problem ✌🏻
Safari on iOS is usually the biggest pain in the butt for me when trying to make a website work across devices, seems like they've always got something implemented differently than everyone else 😬
Anyways, good luck!

**Comment by gdhebling** [comment]
Hei Lukas! 👋
Sorry I didn't get back to you earlier. Could you kindly check if the issues you've mentioned have been resolved? 
I can't seem to emulate them from my end, but I did try to improve a couple of media queries! Would be great to hear from you again. Thank you! 🙂

**Comment by luk-str** [comment]
Hei hei Guilherme! Just checked in both browsers and the bugs are gone, good work 🤘🏻

**Comment by gdhebling** [comment]
Thanks, Lukas! Glad it worked out. I appreciate the help 🙌🏻
